# Generated by Django 5.2.12 on 2026-04-04 16:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('hijama', 'Hijama'), ('ruqyah', 'Ruqyah'), ('counseling', 'Counseling'), ('assessment', 'Assessment')], max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_bn', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('description_bn', models.TextField(blank=True, default='')),
                ('full_description', models.TextField(blank=True, default='')),
                ('full_description_bn', models.TextField(blank=True, default='')),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('price_bdt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=True)),
                ('is_offline', models.BooleanField(default=True)),
                ('icon_name', models.CharField(blank=True, default='', max_length=50)),
                ('image_url', models.URLField(blank=True, default='')),
                ('benefits', models.JSONField(default=list)),
                ('benefits_bn', models.JSONField(default=list)),
                ('what_to_expect', models.JSONField(default=list)),
                ('what_to_expect_bn', models.JSONField(default=list)),
                ('hijama_pricing', models.JSONField(blank=True, null=True)),
                ('mode_pricing', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'services',
                'ordering': ['name'],
            },
        ),
    ]
