# Generated by Django 5.2.12 on 2026-04-04 16:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('form_data', models.JSONField(help_text='4-step assessment form data (step1-4)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('assigned', 'Assigned')], default='pending', max_length=10)),
                ('assigned_doctor_name', models.CharField(blank=True, default='', max_length=255)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'health_assessments',
                'ordering': ['-created_at'],
            },
        ),
    ]
